version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "project_mangement_user"
      POSTGRES_PASSWORD: "project_mangement_password"
      POSTGRES_DB: "project_management_db"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
