import type { Metadata } from "next";
import ReduxProvider from "../_components/ReduxProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="h-full flex flex-col justify-center items-center container max-w-[1024px]">
			<ReduxProvider>{children}</ReduxProvider>
		</div>
	);
}
